server {
    listen 80;
    listen [::]:80;
    server_name shwetaungnyunt.tech www.shwetaungnyunt.tech;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name shwetaungnyunt.tech www.shwetaungnyunt.tech;

    root /var/www/shwetaungnyunt.tech;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/shwetaungnyunt.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/shwetaungnyunt.tech/privkey.pem;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:css|js|jpg|jpeg|png|svg|webp|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800, immutable";
        try_files $uri =404;
    }
}
